export const mockSpotifyRefreshToken = {
  access_token: 'accessToken',
  token_type: 'type',
  scope: 'scope',
  expires_in: 1000,
};

export const mockSpotifyTopArtists = [{
  external_urls: { spotify: 'spotify.url' },
  followers: { total: 0 },
  genres: [],
  href: 'h://re.f',
  id: 'id1',
  images: [{ url: 'image.url' }],
  name: 'name1',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  external_urls: { spotify: 'spotify.url' },
  followers: { total: 0 },
  genres: [],
  href: 'h://re.f',
  id: 'id2',
  images: [{ url: 'image.url' }],
  name: 'name2',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  external_urls: { spotify: 'spotify.url' },
  followers: { total: 0 },
  genres: [],
  href: 'h://re.f',
  id: 'id3',
  images: [{ url: 'image.url' }],
  name: 'name3',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}];

export const mockSpotifyTopTracks = [{
  album: {
    external_urls: { spotify: 'albumspotify.url' },
    images: [{ url: 'albumimage.url' }],
    name: 'album1',
  },
  artists: [{
    external_urls: { spotify: 'artistspotify.url' },
    id: 'artistid1',
    name: 'artist1',
  }],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: { spotify: 'spotify.url' },
  href: 'h://re.f',
  id: 'id1',
  is_playable: true,
  name: 'name1',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}, {
  album: {
    external_urls: { spotify: 'albumspotify.url' },
    images: [{ url: 'albumimage.url' }],
    name: 'album2',
  },
  artists: [{
    external_urls: { spotify: 'artistspotify.url' },
    id: 'artistid2',
    name: 'artist2',
  }],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: { spotify: 'spotify.url' },
  href: 'h://re.f',
  id: 'id2',
  is_playable: true,
  name: 'name2',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}, {
  album: {
    external_urls: { spotify: 'albumspotify.url' },
    images: [{ url: 'albumimage.url' }],
    name: 'album3',
  },
  artists: [{
    external_urls: { spotify: 'artistspotify.url' },
    id: 'artistid3',
    name: 'artist3',
  }],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: { spotify: 'spotify.url' },
  href: 'h://re.f',
  id: 'id3',
  is_playable: true,
  name: 'name3',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}];

export const mockSpotifyUser = {
  accessToken: 'accessToken',
  expiresIn: 1000,
  profile: {
    _json: {
      display_name: 'Display Name',
      external_urls: { spotify: 'sp://otify.url' },
      followers: { total: 0 },
      href: 'h://re.f',
      id: 'id',
      images: [{ url: 'im://age.url' }],
      type: 'type',
      uri: 'uri',
    },
  },
  refreshToken: 'refreshToken',
};

export const mockTopArtists = [{
  spotifyUrl: 'spotify.url',
  followers: 0,
  genres: [],
  id: 'id1',
  imageUrl: 'image.url',
  name: 'name1',
  popularity: 0,
}, {
  spotifyUrl: 'spotify.url',
  followers: 0,
  genres: [],
  id: 'id2',
  imageUrl: 'image.url',
  name: 'name2',
  popularity: 0,
}, {
  spotifyUrl: 'spotify.url',
  followers: 0,
  genres: [],
  id: 'id3',
  imageUrl: 'image.url',
  name: 'name3',
  popularity: 0,
}];

export const mockTopArtistsOrTracksOptions = {
  limit: 15,
  offset: 0,
  timeRange: 'long_term',
};

export const mockTopTracks = [{
  album: {
    spotifyUrl: 'albumspotify.url',
    imageUrl: 'albumimage.url',
    name: 'album1',
  },
  artists: [{
    id: 'artistid1',
    spotifyUrl: 'artistspotify.url',
    name: 'artist1',
  }],
  durationMs: 0,
  spotifyUrl: 'spotify.url',
  id: 'id1',
  name: 'name1',
  popularity: 0,
  trackNumber: 1,
}, {
  album: {
    spotifyUrl: 'albumspotify.url',
    imageUrl: 'albumimage.url',
    name: 'album2',
  },
  artists: [{
    id: 'artistid2',
    spotifyUrl: 'artistspotify.url',
    name: 'artist2',
  }],
  durationMs: 0,
  spotifyUrl: 'spotify.url',
  id: 'id2',
  name: 'name2',
  popularity: 0,
  trackNumber: 1,
}, {
  album: {
    spotifyUrl: 'albumspotify.url',
    imageUrl: 'albumimage.url',
    name: 'album3',
  },
  artists: [{
    id: 'artistid3',
    spotifyUrl: 'artistspotify.url',
    name: 'artist3',
  }],
  durationMs: 0,
  spotifyUrl: 'spotify.url',
  id: 'id3',
  name: 'name3',
  popularity: 0,
  trackNumber: 1,
}];

export const mockUser = {
  accessToken: 'accessToken',
  expires: 1000,
  profile: {
    displayName: 'Display Name',
    spotifyUrl: 'sp://otify.url',
    followers: 0,
    id: 'id',
    imageUrl: 'im://age.url',
    type: 'type',
  },
  refreshToken: 'refreshToken',
};
