export const mockSpotifyTopArtists = [{
  external_urls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name1',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  external_urls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name2',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  external_urls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name3',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}];

export const mockSpotifyTopTracks = [{
  albums: {},
  artists: [],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: {},
  href: 'h://re.f',
  id: 'id',
  is_playable: true,
  name: 'name1',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}, {
  albums: {},
  artists: [],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: {},
  href: 'h://re.f',
  id: 'id',
  is_playable: true,
  name: 'name2',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}, {
  albums: {},
  artists: [],
  disc_number: 1,
  duration_ms: 0,
  explicit: false,
  external_ids: {},
  external_urls: {},
  href: 'h://re.f',
  id: 'id',
  is_playable: true,
  name: 'name3',
  popularity: 0,
  preview_url: 'pr://eview.url',
  track_number: 1,
  type: 'type',
  uri: 'uri',
}];

export const mockSpotifyUser = {
  accessToken: 'accessTokenaccessTokenaccessTokenaccessTokenaccessTokenaccess' +
  'TokenaccessTokenaccessTokenaccessTokenaccessTokenaccessTokenaccessTokenacc' +
  'essTokenaccessTo',
  expiresIn: 1000,
  profile: {
    _json: {
      display_name: 'Display Name',
      external_urls: {},
      followers: {},
      href: 'h://re.f',
      id: 'id',
      images: [],
      type: 'type',
      uri: 'uri',
    },
  },
  refreshToken: 'refreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshToken' +
  'refreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshToke',
};

export const mockTopArtists = [{
  externalUrls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name1',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  externalUrls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name2',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}, {
  externalUrls: {},
  followers: {},
  genres: {},
  href: 'h://re.f',
  id: 'id',
  images: [],
  name: 'name3',
  popularity: 0,
  type: 'type',
  uri: 'uri',
}];

export const mockTopTracks = [{
  albums: {},
  artists: [],
  discNumber: 1,
  durationMs: 0,
  explicit: false,
  externalIds: {},
  externalUrls: {},
  href: 'h://re.f',
  id: 'id',
  isPlayable: true,
  name: 'name1',
  popularity: 0,
  previewUrl: 'pr://eview.url',
  trackNumber: 1,
  type: 'type',
  uri: 'uri',
}, {
  albums: {},
  artists: [],
  discNumber: 1,
  durationMs: 0,
  explicit: false,
  externalIds: {},
  externalUrls: {},
  href: 'h://re.f',
  id: 'id',
  isPlayable: true,
  name: 'name2',
  popularity: 0,
  previewUrl: 'pr://eview.url',
  trackNumber: 1,
  type: 'type',
  uri: 'uri',
}, {
  albums: {},
  artists: [],
  discNumber: 1,
  durationMs: 0,
  explicit: false,
  externalIds: {},
  externalUrls: {},
  href: 'h://re.f',
  id: 'id',
  isPlayable: true,
  name: 'name3',
  popularity: 0,
  previewUrl: 'pr://eview.url',
  trackNumber: 1,
  type: 'type',
  uri: 'uri',
}];

export const mockUser = {
  accessToken: 'accessTokenaccessTokenaccessTokenaccessTokenaccessTokenaccess' +
  'TokenaccessTokenaccessTokenaccessTokenaccessTokenaccessTokenaccessTokenacc' +
  'essTokenaccessTo',
  expires: 1000,
  profile: {
    displayName: 'Display Name',
    externalUrls: {},
    followers: {},
    href: 'h://re.f',
    id: 'id',
    images: [],
    type: 'type',
    uri: 'uri',
  },
  refreshToken: 'refreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshToken' +
  'refreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshTokenrefreshToke',
};
