// Device reducer
export const DEVICE_TYPE_CHANGED = 'DEVICE_TYPE_CHANGED';

// Error
export const CLEAR_ERROR = 'CLEAR_ERROR';

// User
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';
export const LOAD_USER_SUCCEEDED = 'LOAD_USER_SUCCEEDED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';
export const LOGOUT_USER_SUCCEEDED = 'LOGOUT_USER_SUCCEEDED';

// UserStats
export const LOAD_USER_STATS = 'LOAD_USER_STATS';
export const LOAD_USER_STATS_FAILED = 'LOAD_USER_STATS_FAILED';
export const LOAD_USER_STATS_FINISHED = 'LOAD_USER_STATS_FINISHED';
export const LOAD_USER_STATS_TOP_ARTISTS_FAILED =
  'LOAD_USER_STATS_TOP_ARTISTS_FAILED';
export const LOAD_USER_STATS_TOP_ARTISTS_SUCCEEDED =
  'LOAD_USER_STATS_TOP_ARTISTS_SUCCEEDED';
export const LOAD_USER_STATS_TOP_TRACKS_FAILED =
  'LOAD_USER_STATS_TOP_TRACKS_FAILED';
export const LOAD_USER_STATS_TOP_TRACKS_SUCCEEDED =
  'LOAD_USER_STATS_TOP_TRACKS_SUCCEEDED';
